       /*Ciudades  y regiones de alemania*/
       if(job.location.indexOf("Augsburg")>-1){job.location = "Augsburg, DE";}
       if(job.location.indexOf("Bad Homburg")>-1){job.location = "Bad Homburg, DE";}
       if(job.location.indexOf("Bad Kreuznach")>-1){job.location = "Bad Kreuznach, DE";}
       if(job.location.indexOf("Bergisch Gladbach")>-1){job.location = "Bergisch Gladbach, DE";}
       if(job.location.indexOf("Köpenick")>-1){job.location = "Köpenick, Berlin, DE";}
       if(job.location.indexOf("Steglitz")>-1){job.location = "Steglitz, Berlin, DE";}
       if(job.location.indexOf("Spandau")>-1){job.location = "Spandau, Berlin, DE";}
       if(job.location.indexOf("Pankow")>-1){job.location = "Pankow, Berlin, DE";}
       if(job.location.indexOf("Braunschweig")>-1){job.location = "Braunschweig, DE";}
       if(job.location.indexOf("Dessau")>-1){job.location = "Dessau, DE";}
       if(job.location.indexOf("Dinslaken")>-1){job.location = "Dinslaken, DE";}
       if(job.location.indexOf("Dorsten")>-1){job.location = "Dorsten, DE";}
       if(job.location.indexOf("Dortmund")>-1){job.location = "Dortmund, DE";}
       if(job.location.indexOf("Dresden")>-1){job.location = "Dresden, DE";}
       if(job.location.indexOf("Detmold")>-1){job.location = "Detmold, DE";}
       if(job.location.indexOf("Düren")>-1){job.location = "Düren, DE";}
       if(job.location.indexOf("Frankfurt")>-1){job.location = "Frankfurt, DE";}
       if(job.location.indexOf("Dallgow-Döberitz")>-1){job.location = "Dallgow-Döberitz, DE";}
       if(job.location.indexOf("Coburg")>-1){job.location = "Coburg, DE";}
       if(job.location.indexOf("Celle")>-1){job.location = "Celle, DE";}
       if(job.location.indexOf("Bonn")>-1){job.location = "Bonn, DE";}
       if(job.location.indexOf("Bremen")>-1){job.location = "Bremen, DE";}
       if(job.location.indexOf("Bocholt")>-1){job.location = "Bocholt, DE";}
       if(job.location.indexOf("Berlin")>-1){job.location = "Berlin, DE";}
       if(job.location.indexOf("Mannheim")>-1){job.location = "Mannheim, DE";}
       if(job.location.indexOf("Mainz")>-1){job.location = "Mainz, DE";}
       if(job.location.indexOf("München")>-1){job.location = "München, DE";}
       if(job.location.indexOf("Wildau")>-1){job.location = "Wildau, DE";}
       if(job.location.indexOf("Wetzlar")>-1){job.location = "Wetzlar, DE";}
       if(job.location.indexOf("Stuttgart")>-1){job.location = "Stuttgart, DE";}
       if(job.location.indexOf("Unna")>-1){job.location = "Unna, DE";}
       if(job.location.indexOf("St. Pölten")>-1){job.location = "St. Pölten, Austria";}
       if(job.location.indexOf("Schweinfurt")>-1){job.location = "Schweinfurt, DE";}
       if(job.location.indexOf("Saarbrücken")>-1){job.location = "Saarbrücken, DE";}
       if(job.location.indexOf("Rostock")>-1){job.location = "Rostock, DE";}
       if(job.location.indexOf("Landau")>-1){job.location = "Landau, DE";}
       if(job.location.indexOf("Laatzen")>-1){job.location = "Laatzen, DE";}
       if(job.location.indexOf("Koblenz")>-1){job.location = "Koblenz, DE";}
       if(job.location.indexOf("Kiel")>-1){job.location = "Kiel, DE";}
       if(job.location.indexOf("Hildesheim")>-1){job.location = "Hildesheim, DE";}
       if(job.location.indexOf("Hannover")>-1){job.location = "Hannover, DE";}
       if(job.location.indexOf("Hanau")>-1){job.location = "Hanau, DE";}
       if(job.location.indexOf("Hamburg")>-1){job.location = "Hamburg, DE";}
       if(job.location.indexOf("Essen")>-1){job.location = "Essen, DE";}
       if(job.location.indexOf("Leipzig")>-1){job.location = "Leipzig, DE";}
       if(job.location.indexOf("Duisburg")>-1){job.location = "Duisburg, DE";}
       if(job.location.indexOf("Düsseldorf")>-1){job.location = "Düsseldorf, DE";}
       if(job.location.indexOf("Iserlohn")>-1){job.location = "Iserlohn, DE";}
       if(job.location.indexOf("Heilbronn")>-1){job.location = "Heilbronn, DE";}
       if(job.location.indexOf("Gera")>-1){job.location = "Gera, DE";}
       if(job.location.indexOf("Jena")>-1){job.location = "Jena, DE";}
       if(job.location.indexOf("Münster")>-1){job.location = "Münster, DE";}
       if(job.location.indexOf("Mönchengladbach")>-1){job.location = "Mönchengladbach, DE";}
       if(job.location.indexOf("Pforzheim")>-1){job.location = "Pforzheim, DE";}
       if(job.location.indexOf("Siegen")>-1){job.location = "Siegen, DE";}
       if(job.location.indexOf("Köln")>-1){job.location = "Köln, DE";}
       if(job.location.indexOf("Ingolstadt")>-1){job.location = "Ingolstadt, DE";}
       if(job.location.indexOf("Rosenheim")>-1){job.location = "Rosenheim, DE";}
       if(job.location.indexOf("Aachen")>-1){job.location = "Aachen, DE";}
       if(job.location.indexOf("Krefeld")>-1){job.location = "Krefeld, DE";}
       if(job.location.indexOf("Flensburg")>-1){job.location = "Flensburg, DE";}
       if(job.location.indexOf("Herford")>-1){job.location = "Herford, DE";}
       if(job.location.indexOf("Zwickau")>-1){job.location = "Zwickau, DE";}
       if(job.location.indexOf("Halle")>-1){job.location = "Halle, DE";}
       if(job.location.indexOf("Krefeld")>-1){job.location = "Krefeld, DE";}
       if(job.location.indexOf("Neuss")>-1){job.location = "Neuss, DE";}
       if(job.location.indexOf("Brandenburg ")>-1){job.location = "Brandenburg , DE";}
       if(job.location.indexOf("Moers")>-1){job.location = "Moers, DE";}
       if(job.location.indexOf("Bernburg")>-1){job.location = "Bernburg, DE";}
       if(job.location.indexOf("Ulm")>-1){job.location = "Ulm, DE";}
       if(job.location.indexOf("Stade")>-1){job.location = "Stade, DE";}
       if(job.location.indexOf("Rastatt")>-1){job.location = "Rastatt, DE";} 
       if(job.location.indexOf("Oberursel")>-1){job.location = "Oberursel, DE";}
       if(job.location.indexOf("Bruchsal")>-1){job.location = "Bruchsal, DE";}
       if(job.location.indexOf("Dormagen")>-1){job.location = "Dormagen, DE";}
       if(job.location.indexOf("Fürstenfeldbruck")>-1){job.location = "Fürstenfeldbruck, DE";}
       if(job.location.indexOf("Kassel")>-1){job.location = "Kassel, DE";}  
       if(job.location.indexOf("Gotha")>-1){job.location = "Gotha, DE";}
       if(job.location.indexOf("Hameln")>-1){job.location = "Hameln, DE";}
       if(job.location.indexOf("Neuwied")>-1){job.location = "Neuwied, DE";}  
       if(job.location.indexOf("Tübingen")>-1){job.location = "Tübingen, DE";}
       if(job.location.indexOf("Böblingen")>-1){job.location = "Böblingen, DE";}
       if(job.location.indexOf("Mühldorf am Inn")>-1){job.location = "Mühldorf am Inn, DE";}  
       if(job.location.indexOf("Recklinghausen")>-1){job.location = "Recklinghausen, DE";}
       if(job.location.indexOf("Itzehoe")>-1){job.location = "Itzehoe, DE";}
       if(job.location.indexOf("Frechen")>-1){job.location = "Frechen, DE";} 
       if(job.location.indexOf("Mölln")>-1){job.location = "Mölln, DE";}
       if(job.location.indexOf("Nürnberg")>-1){job.location = "Nürnberg, DE";}